# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/about_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(460, 380)
        self.layout_dialog = QtWidgets.QVBoxLayout(AboutDialog)
        self.layout_dialog.setContentsMargins(24, 24, 24, 20)
        self.layout_dialog.setSpacing(18)
        self.layout_dialog.setObjectName("layout_dialog")
        self.layout_header = QtWidgets.QHBoxLayout()
        self.layout_header.setSpacing(18)
        self.layout_header.setObjectName("layout_header")
        self.lbl_about_icon = QtWidgets.QLabel(AboutDialog)
        self.lbl_about_icon.setMinimumSize(QtCore.QSize(72, 72))
        self.lbl_about_icon.setMaximumSize(QtCore.QSize(72, 72))
        self.lbl_about_icon.setText("")
        self.lbl_about_icon.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_about_icon.setObjectName("lbl_about_icon")
        self.layout_header.addWidget(self.lbl_about_icon)
        self.layout_identity = QtWidgets.QVBoxLayout()
        self.layout_identity.setSpacing(4)
        self.layout_identity.setObjectName("layout_identity")
        self.lbl_about_name = QtWidgets.QLabel(AboutDialog)
        self.lbl_about_name.setObjectName("lbl_about_name")
        self.layout_identity.addWidget(self.lbl_about_name)
        self.lbl_about_version = QtWidgets.QLabel(AboutDialog)
        self.lbl_about_version.setObjectName("lbl_about_version")
        self.layout_identity.addWidget(self.lbl_about_version)
        spacerItem = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.layout_identity.addItem(spacerItem)
        self.lbl_about_author = QtWidgets.QLabel(AboutDialog)
        self.lbl_about_author.setObjectName("lbl_about_author")
        self.layout_identity.addWidget(self.lbl_about_author)
        self.lbl_about_link = QtWidgets.QLabel(AboutDialog)
        self.lbl_about_link.setText("")
        self.lbl_about_link.setOpenExternalLinks(True)
        self.lbl_about_link.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction)
        self.lbl_about_link.setObjectName("lbl_about_link")
        self.layout_identity.addWidget(self.lbl_about_link)
        spacerItem1 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.layout_identity.addItem(spacerItem1)
        self.layout_header.addLayout(self.layout_identity)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_header.addItem(spacerItem2)
        self.layout_dialog.addLayout(self.layout_header)
        self.about_divider = QtWidgets.QFrame(AboutDialog)
        self.about_divider.setMinimumSize(QtCore.QSize(0, 1))
        self.about_divider.setMaximumSize(QtCore.QSize(16777215, 1))
        self.about_divider.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.about_divider.setObjectName("about_divider")
        self.layout_dialog.addWidget(self.about_divider)
        self.lbl_about_licence = QtWidgets.QLabel(AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_about_licence.sizePolicy().hasHeightForWidth())
        self.lbl_about_licence.setSizePolicy(sizePolicy)
        self.lbl_about_licence.setText("")
        self.lbl_about_licence.setWordWrap(True)
        self.lbl_about_licence.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_about_licence.setOpenExternalLinks(True)
        self.lbl_about_licence.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction)
        self.lbl_about_licence.setObjectName("lbl_about_licence")
        self.layout_dialog.addWidget(self.lbl_about_licence)
        self.button_box = QtWidgets.QDialogButtonBox(AboutDialog)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_box.setObjectName("button_box")
        self.layout_dialog.addWidget(self.button_box)

        self.retranslateUi(AboutDialog)
        self.button_box.rejected.connect(AboutDialog.reject) # type: ignore
        self.button_box.accepted.connect(AboutDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.lbl_about_name.setText(_translate("AboutDialog", "Vobot Now Playing"))
        self.lbl_about_version.setText(_translate("AboutDialog", "Version"))
        self.lbl_about_author.setText(_translate("AboutDialog", "Author"))
